# Generated by Django 3.1.6 on 2021-02-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20191025_1852'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together={('event', 'start', 'end')},
        ),
    ]
